### ISSUE TITLE
hubUrl set to the wrong value?

### ISSUE THREAD

**Issue by ssaloisbellerose** [BroadSoft-Xtended/DeveloperPortalDocs#13]
https://developer.broadsoftlabs.com/#/app/documentation/Hub/ApiAuthorization.md

I don't know if I misunderstand the doc or if its a bug in hub, but the hubUrl parameter is set to a different value then the one in the sample code.

In the sample code, the hard coded url used is https://core.broadsoftlabs.com/v1/SMSHub/<username>/auth

However, the hubUrl returned to me by hub is: https://core.broadsoftlabs.com:443&lang=en_US

**Comment by joncodo** [comment]
This is not a bug. It is simply the base url for the hub api that you are working with. If you had worked on a different environment, you would have seen a different url come back. It can be used to do some hacky things to debug hub if necessary but is not part of the main api
