### ISSUE TITLE
Use different value for the auth and username in the example

### ISSUE THREAD

**Issue by ssaloisbellerose** [BroadSoft-Xtended/DeveloperPortalDocs#15]
https://developer.broadsoftlabs.com/#/app/documentation/Hub/ApiAuthorization.md

In this example:

var options = {
    method: 'POST',
    uri: 'https://core.broadsoftlabs.com/v1/' + req.session.appName + '/jodonnell@broadsoft.com/auth',
    body: {
      hubLoginToken: req.session.hubLoginToken,
      auth: 'jodonnell@broadsoft.com'
    },
    json: true
  };

Please use different values for the auth and the username. It seems like they are both the same thing otherwise.

**Comment by joncodo** [comment]
done
