### ISSUE TITLE
Clarify the Push Notification

### ISSUE THREAD

**Issue by ssaloisbellerose** [BroadSoft-Xtended/DeveloperPortalDocs#19]
https://developer.broadsoftlabs.com/#/app/documentation/Hub/PushNotifications.md

This doc page is not really clear. 
I would change " This means that Hub will call your app for contextual and notifications data." to: "This means that hub will request the latest contextual and notification data by sending POST requests to https://<baseUrl>/:app/notifications and https://<yourBaseUrl>/:app/timeline"

I would also add a step 7:
"The hub app returns the updated contextual data and the new notifications count"

Another thing that confused me at first was that I had the impression that the push request was sent to the hub app instead of directly to hub. So maybe add a sentence to make it really clear since the URLs for the app vs hub are very similar 

For example (from the docs):
https://<hubBaseUrl>/:appName/:username/push (hub)
vs
https://<baseUrl>/:app/notifications (hub app server)

**Comment by joncodo** [comment]
done
