### ISSUE TITLE
Clarify the username

### ISSUE THREAD

**Issue by ssaloisbellerose** [BroadSoft-Xtended/DeveloperPortalDocs#21]
The username is used in a couple of urls in
- https://developer.broadsoftlabs.com/#/app/documentation/Hub/ApiAuthorization.md
- https://developer.broadsoftlabs.com/#/app/documentation/Hub/PushNotifications.md

However, it is not clear that this is not the team one username, but a username chosen by the hub app.

**Comment by joncodo** [comment]
added this:

## Username

In many hub routes, you will need to have a username sent. You may also receive this username. This is the username that Hub has for your user. An example could be that you had sent the username to Hub for authentication. Once this happens, this is the username that Hub will send back to you with each call where applicable.
