### ISSUE TITLE
Add a picture of the contextual tab in the "Updating contextual" page

### ISSUE THREAD

**Issue by ssaloisbellerose** [BroadSoft-Xtended/DeveloperPortalDocs#22]
There is already a picture of the contextual tab in the overview page, but there is not one in "Updating contextual". If a user reads everything in order, then a couple of hours may pass between overview and updating contextual, so a picture would help the user to remember what the contextual tab is when he gets to the "updating contextual" page.

**Comment by joncodo** [comment]
Done
